/*
 * This file is generated by jOOQ.
 */
package org.jooq.inova.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.inova.tables.Formandos;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FormandosRecord extends UpdatableRecordImpl<FormandosRecord> implements Record6<Integer, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>inova.formandos.idformandos</code>.
     */
    public void setIdformandos(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inova.formandos.idformandos</code>.
     */
    public Integer getIdformandos() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inova.formandos.nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>inova.formandos.nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>inova.formandos.morada</code>.
     */
    public void setMorada(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>inova.formandos.morada</code>.
     */
    public String getMorada() {
        return (String) get(2);
    }

    /**
     * Setter for <code>inova.formandos.codpostal</code>.
     */
    public void setCodpostal(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>inova.formandos.codpostal</code>.
     */
    public String getCodpostal() {
        return (String) get(3);
    }

    /**
     * Setter for <code>inova.formandos.telefone</code>.
     */
    public void setTelefone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>inova.formandos.telefone</code>.
     */
    public String getTelefone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>inova.formandos.idcursos</code>.
     */
    public void setIdcursos(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>inova.formandos.idcursos</code>.
     */
    public Integer getIdcursos() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Formandos.FORMANDOS.IDFORMANDOS;
    }

    @Override
    public Field<String> field2() {
        return Formandos.FORMANDOS.NOME;
    }

    @Override
    public Field<String> field3() {
        return Formandos.FORMANDOS.MORADA;
    }

    @Override
    public Field<String> field4() {
        return Formandos.FORMANDOS.CODPOSTAL;
    }

    @Override
    public Field<String> field5() {
        return Formandos.FORMANDOS.TELEFONE;
    }

    @Override
    public Field<Integer> field6() {
        return Formandos.FORMANDOS.IDCURSOS;
    }

    @Override
    public Integer component1() {
        return getIdformandos();
    }

    @Override
    public String component2() {
        return getNome();
    }

    @Override
    public String component3() {
        return getMorada();
    }

    @Override
    public String component4() {
        return getCodpostal();
    }

    @Override
    public String component5() {
        return getTelefone();
    }

    @Override
    public Integer component6() {
        return getIdcursos();
    }

    @Override
    public Integer value1() {
        return getIdformandos();
    }

    @Override
    public String value2() {
        return getNome();
    }

    @Override
    public String value3() {
        return getMorada();
    }

    @Override
    public String value4() {
        return getCodpostal();
    }

    @Override
    public String value5() {
        return getTelefone();
    }

    @Override
    public Integer value6() {
        return getIdcursos();
    }

    @Override
    public FormandosRecord value1(Integer value) {
        setIdformandos(value);
        return this;
    }

    @Override
    public FormandosRecord value2(String value) {
        setNome(value);
        return this;
    }

    @Override
    public FormandosRecord value3(String value) {
        setMorada(value);
        return this;
    }

    @Override
    public FormandosRecord value4(String value) {
        setCodpostal(value);
        return this;
    }

    @Override
    public FormandosRecord value5(String value) {
        setTelefone(value);
        return this;
    }

    @Override
    public FormandosRecord value6(Integer value) {
        setIdcursos(value);
        return this;
    }

    @Override
    public FormandosRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FormandosRecord
     */
    public FormandosRecord() {
        super(Formandos.FORMANDOS);
    }

    /**
     * Create a detached, initialised FormandosRecord
     */
    public FormandosRecord(Integer idformandos, String nome, String morada, String codpostal, String telefone, Integer idcursos) {
        super(Formandos.FORMANDOS);

        setIdformandos(idformandos);
        setNome(nome);
        setMorada(morada);
        setCodpostal(codpostal);
        setTelefone(telefone);
        setIdcursos(idcursos);
    }
}
