/*
 * This file is generated by jOOQ.
 */
package org.jooq.inova;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.inova.tables.Cursodis;
import org.jooq.inova.tables.Cursos;
import org.jooq.inova.tables.Disciplinas;
import org.jooq.inova.tables.Formandos;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Inova extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>inova</code>
     */
    public static final Inova INOVA = new Inova();

    /**
     * The table <code>inova.cursodis</code>.
     */
    public final Cursodis CURSODIS = Cursodis.CURSODIS;

    /**
     * The table <code>inova.cursos</code>.
     */
    public final Cursos CURSOS = Cursos.CURSOS;

    /**
     * The table <code>inova.disciplinas</code>.
     */
    public final Disciplinas DISCIPLINAS = Disciplinas.DISCIPLINAS;

    /**
     * The table <code>inova.formandos</code>.
     */
    public final Formandos FORMANDOS = Formandos.FORMANDOS;

    /**
     * No further instances allowed
     */
    private Inova() {
        super("inova", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Cursodis.CURSODIS,
            Cursos.CURSOS,
            Disciplinas.DISCIPLINAS,
            Formandos.FORMANDOS);
    }
}
