/*
 * This file is generated by jOOQ.
 */
package org.jooq.inova;


import org.jooq.inova.tables.Cursodis;
import org.jooq.inova.tables.Cursos;
import org.jooq.inova.tables.Disciplinas;
import org.jooq.inova.tables.Formandos;


/**
 * Convenience access to all tables in inova.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>inova.cursodis</code>.
     */
    public static final Cursodis CURSODIS = Cursodis.CURSODIS;

    /**
     * The table <code>inova.cursos</code>.
     */
    public static final Cursos CURSOS = Cursos.CURSOS;

    /**
     * The table <code>inova.disciplinas</code>.
     */
    public static final Disciplinas DISCIPLINAS = Disciplinas.DISCIPLINAS;

    /**
     * The table <code>inova.formandos</code>.
     */
    public static final Formandos FORMANDOS = Formandos.FORMANDOS;
}
